# ODE docker compose file
# Copyright (C) 2018 Project-ODE

version: '3.5'
services:
  testdb:
    image: mdillon/postgis
    environment:
      - POSTGRES_USER=test
    networks:
      - db

  feature_service:
    build: FeatureService
    depends_on:
      - testdb
    ports:
      - "7231:7231"
    environment:
      - NODE_ENV=test
    command: bash -c "sleep 1; knex migrate:latest && knex seed:run && npm start"
    networks:
      - db

  front_manager:
    build: FrontManager
    depends_on:
      - feature_service
    ports:
      - "3000:3000"
    command: npm start
    networks:
      - front
      
networks:
  front:
  db: