# ODE docker compose file
# Copyright (C) 2017 Project-ODE

# author: Alexandre Degurse

version: '3.1'
services:

  feature_engine:
    build: feature_engine
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=ode-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - middleware

  # kibana:
  #   image: "docker.elastic.co/kibana/kibana:6.2.2"
  #   container_name: kibana
  #   ports:
  #     - 5601:5601
  #   networks:
  #     - middleware

  feature_service:
    build: "feature_service"
    container_name: feature_service
    environment:
      - NODE_ENV=production
    networks:
      - middleware

  nginx:
    ## As of now, there is no repository for frontend. Thus, no image is build,
    ## nginx's default image is used.
    # build: "nginx"
    image: nginx:1.13.9
    container_name: nginx
    volumes:
      - ./nginx/config:/etc/nginx:ro
      - ./nginx/static:/var/www/edo/static:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - middleware

networks:
  middleware:
  backend:
